name: "leptosfmt formatter"
description: "Formatter for the leptos view! macros"

inputs:
  args:
    description: "leptosfmt arguments (https://github.com/bram209/leptosfmt?tab=readme-ov-file#usage)"
    default: "./**/*.rs --check"
    required: false
  leptosfmtVersion:
    description: "Use custom version of leptosfmt"
    default: 0.1.32
    required: false
  output:
    description: "Summary output file path"
    default: "leptosfmt_output.txt"
    required: false
  debug:
    description: "Enable debug output"
    default: "false"
    required: false

outputs:
  exit_code:
    description: "The exit code returned from leptosfmt"
    value: ${{ steps.run-leptosfmt.outputs.exit_code }}

runs:
  using: "composite"
  steps:
    - name: Set up environment
      run: |
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        mkdir -p "$HOME/.local/bin"
      shell: bash

    - name: Clean up existing leptosfmt files
      run: |
        # Remove any existing leptosfmt binaries or archives to prevent conflicts
        rm -f $(which leptosfmt)
      shell: bash

    - name: Download and extract leptosfmt
      id: leptosfmt-setup
      run: |
        # Determine filename and download URL based on version
        FILENAME="leptosfmt-${LEPTOSFMT_VERSION}-x86_64-unknown-linux-musl.tar.gz"
        DOWNLOAD_URL="https://github.com/bram209/leptosfmt/releases/download/${LEPTOSFMT_VERSION}/${FILENAME}"

        echo "Downloading from: ${DOWNLOAD_URL}"
        curl -sfLO "${DOWNLOAD_URL}"

        echo "Extracting ${FILENAME}"
        tar -xvzf "${FILENAME}"

        # Output filename for use in later steps
        echo "filename=${FILENAME}" >> $GITHUB_OUTPUT
      env:
        LEPTOSFMT_VERSION: ${{ inputs.leptosfmtVersion }}
      shell: bash

    - name: Install leptosfmt
      run: |
        install -t "$HOME/.local/bin" -D leptosfmt
      shell: bash

    - name: Clean up installation files
      run: |
        rm -f "${{ steps.leptosfmt-setup.outputs.filename }}"
      shell: bash

    - name: Run leptosfmt
      id: run-leptosfmleptosfmt
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        # https://github.com/actions/runner/issues/665
        INPUT_ARGS: ${{ inputs.ARGS }}
        INPUT_OUTPUT: ${{ inputs.OUTPUT }}
        INPUT_DEBUG: ${{ inputs.DEBUG }}
      shell: bash
branding:
  icon: "external-link"
  color: "purple"
